<?php
/*
* PinaCMS
* 
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
* LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
* THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
* @copyright © 2010 Dobrosite ltd.
*/

if (!defined('PATH')){ exit; }



$db = getDB();
$db->query("
CREATE TABLE IF NOT EXISTS `cody_menu` (
	`menu_id` int(11) NOT NULL AUTO_INCREMENT,
	`site_id` int(10) NOT NULL DEFAULT '0',
	`menu_key` varchar(64) NOT NULL DEFAULT '',
	`menu_title` varchar(255) NOT NULL DEFAULT '',
	`menu_order` int(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`menu_id`),
	UNIQUE KEY(`site_id`, `menu_key`)
) ENGINE=".DB_DEFAULT_ENGINE." DEFAULT CHARSET=utf8;
");

$db->query("
CREATE TABLE IF NOT EXISTS `cody_menu_item` (
	`menu_item_id` int(11) NOT NULL AUTO_INCREMENT,
	`menu_id` int(11) NOT NULL DEFAULT '0',
	`site_id` int(11) NOT NULL DEFAULT '0',
	`menu_item_title` varchar(255) NOT NULL DEFAULT '',
	`menu_item_link` varchar(255) NOT NULL DEFAULT '',
	`url_action` varchar(32) NOT NULL DEFAULT '',
	`url_params` varchar(128) NOT NULL DEFAULT '',
	`menu_item_enabled` varchar(1) NOT NULL DEFAULT 'Y',
	`menu_item_order` int(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`menu_item_id`),
	KEY(`site_id`, `url_action`, `url_params`),
	KEY(`site_id`, `menu_id`)
) ENGINE=".DB_DEFAULT_ENGINE." DEFAULT CHARSET=utf8;
");