<?php
/*
* PinaCMS
* 
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
* LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
* THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
* @copyright © 2010 Dobrosite ltd.
*/

if (!defined('PATH')){ exit; }



$db = getDB();
$db->query("
CREATE TABLE IF NOT EXISTS `cody_post_comment` (
	`comment_id` int(11) NOT NULL AUTO_INCREMENT,
	`answer_comment_id` int(11) NOT NULL DEFAULT '0',
	`site_id` int(11) NOT NULL DEFAULT '0',
	`post_id` int(11) NOT NULL DEFAULT '0',
	`visitor_name` varchar(32) NOT NULL DEFAULT '',
	`visitor_email` varchar(32) NOT NULL DEFAULT '',
	`visitor_ip` varchar(32) NOT NULL DEFAULT '',
	`visitor_site` varchar(32) NOT NULL DEFAULT '',
	`comment_message` text NOT NULL,
	`comment_approved` varchar(1) NOT NULL DEFAULT 'N',
	`comment_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`comment_updated` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
	`user_id` int(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`comment_id`),
	KEY `ps` (`post_id`,`site_id`)
) ENGINE=".DB_DEFAULT_ENGINE." DEFAULT CHARSET=utf8;
");

$db->query("
CREATE TABLE IF NOT EXISTS `cody_post_rating` (
	`rating_id` INT(11) NOT NULL AUTO_INCREMENT,
	`post_id` INT(11) NOT NULL DEFAULT '0',
	`user_id` INT(11) NOT NULL DEFAULT '0',
	`rating` INT(1) NOT NULL DEFAULT '0',
	`site_id` INT(11) NOT NULL DEFAULT '0',

	PRIMARY KEY(`rating_id`)
) ENGINE=".DB_DEFAULT_ENGINE." DEFAULT CHARSET=utf8;
");

$db->query("
CREATE TABLE IF NOT EXISTS `cody_post_comment_rating` (
	`rating_id` INT(11) NOT NULL AUTO_INCREMENT,
	`comment_id` INT(11) NOT NULL DEFAULT '0',
	`user_id` INT(11) NOT NULL DEFAULT '0',
	`rating` INT(1) NOT NULL DEFAULT '0',
	`site_id` INT(11) NOT NULL DEFAULT '0',

	PRIMARY KEY(`rating_id`)

) ENGINE = ".DB_DEFAULT_ENGINE." DEFAULT CHARSET=utf8;
");

	
